services:

  # database service
  db:
    image: postgres:16.3
    container_name: db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - transcendence
    restart: always

  # web server service
  webserver:
    build: src/webserver/
    image: webserver
    container_name: webserver
    volumes:
      - ./src/webserver/html:/usr/share/nginx/html
    ports:
      - "49300:443"
    networks:
      - transcendence
    depends_on:
      - transcendence
    restart: always

  # transcendence backend service
  transcendence:
    build: src/transcendence
    image: transcendence
    container_name: transcendence
    env_file:
      - .env
    volumes:
      - ./src/transcendence/app:/app
    command: /bin/start
    networks:
      - transcendence
    depends_on:
      - db
    restart: always

volumes:
  db_data:
    name: db_data
    driver: local

networks:

  # Transcendence network
  transcendence:
    name: transcendence
    driver: bridge
