services:

  # database service
  db:
    image: postgres:16.3
    container_name: db
    env_file:
      - .env
    volumes:
      - ./src/postgres/data:/var/lib/postgresql/data
    networks:
      - transcendence
    restart: always

  # web server service
  webserver:
    build: src/nginx/
    image: webserver
    container_name: webserver
    volumes:
      - ./src/nginx/conf:/etc/nginx/conf.d
      - ./src/nginx/html:/usr/share/nginx/html
    ports:
      - "443:443"
    networks:
      - transcendence
    depends_on:
      - transcendence
    restart: always

  # transcendence backend service
  transcendence:
    build: src/django/
    image: transcendence
    container_name: transcendence
    env_file:
      - .env
    volumes:
      - ./src/django/app:/app
    command: python manage.py runserver 0.0.0.0:8000 # use this command for development
    # command: gunicorn --bind 0.0.0.0:8000 transcendence.wsgi:application # use this command for production
    networks:
      - transcendence
    depends_on:
      - db
    restart: always

networks:

  # Transcendence network
  transcendence:
    name: transcendence
    driver: bridge
