services:

  # database service
  db:
    image: postgres:16.3
    container_name: db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - transcendence

  # web server service
  nginx:
    build: src/nginx/
    image: nginx
    container_name: nginx
    volumes:
      - ./src/nginx/html:/usr/share/nginx/html
    ports:
      - "49300:443"
    networks:
      - transcendence
    depends_on:
      - django

  # transcendence backend service
  django:
    build: src/django
    image: django
    container_name: django
    env_file:
      - .env
    volumes:
      - ./src/django/app:/app
    command: /bin/start dev # start the django server in development mode
    # command: /bin/start prod # start the django server in production mode
    networks:
      - transcendence
    depends_on:
      - db

volumes:

  # database data volume
  db_data:
    name: db_data
    driver: local

networks:

  # Transcendence network
  transcendence:
    name: transcendence
    driver: bridge
