services:

  # transcendence database service
  db:
    image: postgres:16.4-alpine3.20
    container_name: db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - transcendence
    restart: on-failure

  # transcendence frontend service
  nginx:
    build: src/nginx/
    image: nginx
    container_name: nginx
    volumes:
      - ./src/nginx/html:/usr/share/nginx/html
      - images:/images
    ports:
      - "49300:443"
    networks:
      - transcendence
    depends_on:
      - django
    restart: on-failure

  # transcendence backend service
  django:
    build: src/django
    image: django
    container_name: django
    env_file:
      - .env
    volumes:
      - ./src/django/app:/app
      - images:/images
    command: /bin/start dev # start the django server in development mode
    # command: /bin/start prod # start the django server in production mode
    networks:
      - transcendence
    depends_on:
      - db
      - redis
    restart: on-failure

  # transcendence layer service
  redis:
    image: redis:7.4.0-alpine
    container_name: redis
    networks:
      - transcendence
    restart: on-failure

volumes:

  # database data volume
  db_data:
    name: db_data
    driver: local

  # images volume
  images:
    name: images
    driver: local

networks:

  # Transcendence network
  transcendence:
    name: transcendence
    driver: bridge
