services:

  # database service
  db:
    image: postgres:16.3
    container_name: db
    env_file:
      - .env
    volumes:
      - ~/goinfre/db/data:/var/lib/postgresql/data
    networks:
      - transcendence
    restart: always

  # web server service
  webserver:
    build: src/webserver/
    image: webserver
    container_name: webserver
    volumes:
      - ./src/webserver/html:/usr/share/nginx/html
    ports:
      - "49300:443"
      - "443:443"
    networks:
      - transcendence
    depends_on:
      - transcendence
    restart: always

  # transcendence backend service
  transcendence:
    build: src/transcendence
    image: transcendence
    container_name: transcendence
    env_file:
      - .env
    volumes:
      - ./src/transcendence/app:/app
    command: wait-for-postgres $POSTGRES_HOST:$POSTGRES_PORT python manage.py runserver 0.0.0.0:8000 # use this command for development
    # command: wait-for-postgres $POSTGRES_HOST:$POSTGRES_PORT gunicorn --bind 0.0.0.0:8000 transcendence.wsgi:application # use this command for production
    networks:
      - transcendence
    depends_on:
      - db
    restart: always

networks:

  # Transcendence network
  transcendence:
    name: transcendence
    driver: bridge
