#!/bin/sh

set -e

host="$POSTGRES_HOST:$POSTGRES_PORT"

until nc -z "$host" 2>/dev/null; do
  echo "Waiting for $host to be available..."
  sleep 1
done

echo "$host is available - executing command"
python manage.py migrate

if [ "$1" == "dev" ]; then
  echo "Starting development server"
  export DJANGO_DEBUG=True
elif [ "$1" == "prod" ]; then
  echo "Starting production server"
  export DJANGO_DEBUG=False
else
  exit 1
fi

daphne -b 0.0.0.0 -p 8000 transcendence.asgi:application
