# Generated by Django 5.1.3 on 2024-11-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmodel',
            name='matches',
            field=models.ManyToManyField(related_name='matches', to='game.tournamentmatch'),
        ),
    ]
