# Generated by Django 5.0.6 on 2024-07-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.TextField(default='profilePictures/defaults/default0.jpg'),
        ),
    ]
