# Generated by Django 5.0.6 on 2024-08-06 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_profile_friends'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends_request',
            field=models.ManyToManyField(related_name='friends_request_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
