# Generated by Django 5.0.6 on 2024-07-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.TextField(default='profilePicture/default.jpg'),
        ),
    ]
