# Generated by Django 5.0.6 on 2024-09-03 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('player_one_pts', models.IntegerField(default=0)),
                ('player_two_pts', models.IntegerField(default=0)),
                ('player_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_player', to=settings.AUTH_USER_MODEL)),
                ('player_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_theme', models.BooleanField(default=True)),
                ('profile_picture', models.TextField(default='profilePictures/defaults/default0.jpg')),
                ('language_pack', models.CharField(default='lang/EN_UK.json', max_length=40)),
                ('display_name', models.CharField(max_length=15)),
                ('friend_code', models.CharField(max_length=20, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('id42', models.IntegerField(default=0)),
                ('blocked_users', models.ManyToManyField(related_name='block_user_list', to=settings.AUTH_USER_MODEL)),
                ('friends', models.ManyToManyField(related_name='friends_list', to=settings.AUTH_USER_MODEL)),
                ('friends_request', models.ManyToManyField(related_name='friends_request_list', to=settings.AUTH_USER_MODEL)),
                ('matches', models.ManyToManyField(related_name='matches_history', to='login.match')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
