# Generated by Django 5.1.1 on 2024-09-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friend_code',
        ),
    ]
