# Generated by Django 5.1.2 on 2024-10-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme_name',
            field=models.CharField(default='dark', max_length=10),
        ),
    ]
