# Generated by Django 5.1.2 on 2024-10-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_profile_font_amplifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='use_browser_theme',
            field=models.BooleanField(default=True),
        ),
    ]
